### ISSUE TITLE
Allow Path and String objects for paths

### ISSUE THREAD

**Issue by JoschD** [pylhc/tfs#30]
Not urgent, but if we want to use pathlib in omc3 it should be used here as well so we don't have to convert back to string all the time

**Comment by fsoubelet** [comment]
Probably worth it to have someone look through this (@JoschD ?)
Commit message should be informative enough.

@JoschD @lmalina @Mael-Le-Garrec 
I'd like to get your input on a change.
In logging messages, `f"... {tfs_path.absolute()}"` replaced `f"... {tfs_path:s}"` .
Should this be `.absolute()`? It doesn't take information away of course, but could lead to some very lengthy log lines when running on `afs`.

Let me know, could easily become `f"... {tfs_path}"` and be the path provided to the function making logs.

**Comment by fsoubelet** [comment]
Alright so Travis failed because it went with `pandas 1.0.0rc0`, I have put a hard requirement on `<1.0` for now.

Won't be a problem once @Mael-Le-Garrec get a fix (lord and savior <3, yada yada).

**Comment by Mael-Le-Garrec** [comment]
the bug has been redirected to @JoschD :D

**Comment by fsoubelet** [comment]
Now merged as of commit 77d1e3a, closing.
