### ISSUE TITLE
Remove .indx functionality

### ISSUE THREAD

**Issue by JoschD** [pylhc/tfs#33]
This was implemeted to keep compatibility with metaclass, but it assumes that there is a "NAME" column in the dataframe.
We are usually loading the frames directly with this column as index `read(path, index="NAME")` and never used the `indx`, I think.

Does anyone see a problem with removing that ununsed feature?

@Mael-Le-Garrec @jaimecp89 @rogeliotomas @lmalina @awegsche @mihofer @fsoubelet

**Comment by lmalina** [comment]
I don't see any problem.

**Comment by fsoubelet** [comment]
@JoschD the above commit removes `.indx` and the `_Indx` class created for this purpose.
I think that's all that is needed to consider this issue handled.

Let me know if you see something that was forgotten.

**Comment by JoschD** [comment]
Looks goo. I guess we can skip the "deprecation warning" step and hope no one was using it

**Comment by fsoubelet** [comment]
Actually, since tfs-pandas is already at 1.x, should we?
