### ISSUE TITLE
Remove empty line in write if headers are empty

### ISSUE THREAD

**Issue by JoschD** [pylhc/tfs#43]
When having no headers (headers={}) `tfs.write()` writes out an empty line before the column definitions.

**Comment by fsoubelet** [comment]
Should be implemented in commit fec40cb33345a8af164145dd9788e42e94f6603f. My bad that I forgot the hash to link it here.

A very simple script to check that it works would be:
```python
import numpy
import tfs

frame = tfs.TfsDataFrame(
    index=range(3), columns="a b c d e".split(), data=numpy.random.rand(3, 5), headers={},
)
tfs.write("test.tfs", frame)
```

@JoschD  can you confirm that you're ok with this implementation?
