### ISSUE TITLE
Fix docstrings

### ISSUE THREAD

**Issue by lmalina** [pylhc/tfs#53]
Sphinx parses docstrings a bit strangely. We may also update the example in TfsCollection (should be at least .tfs files).

**Comment by fsoubelet** [comment]
Might be that we need to specify [those settings](https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html#configuration) for the `napoleon` plugin.

**Comment by fsoubelet** [comment]
With a quick local build I can confirm that multi-line parameter definitions are source of issues, and sphinx parses correctly if line returns are started with a tab.

Wrong:
```python
    Args:
        tfs_file_path (Union[pathlib.Path, str]): PosixPath object to the output TFS file. Can be
        a string, but will be cast to a PosixPath object.
```

Correct:
```python
    Args:
        tfs_file_path (Union[pathlib.Path, str]): PosixPath object to the output TFS file. Can be
            a string, but will be cast to a PosixPath object.
```
