### ISSUE TITLE
[Discussion]: Add support for boolean type (%b) in twiss header?

### ISSUE THREAD

**Issue by fsoubelet** [pylhc/tfs#57]
See the last slide of Alexander's presentation [here](https://indico.cern.ch/event/962079/contributions/4047247/attachments/2117138/3562635/06102020_MAD-NG_PS_lattice.pdf): MAD-NG introduces `%b` (boolean) in the twiss headers, which Alexander suggested we support.

Should be a simple case of:
- adding the type to `ID_TO_TYPE` in the handler.
- give a specific handling in `_dtype_to_id_string` when `pdtypes.is_bool_dtype(type_)` is true (currently gives back `%d` as for an integer)
- add tests for the behavior

Important to check: what does MAD-X do when reading these (unknow for it) types? As @JoschD suggested we could create a flag (`compatibility`) for `write_tfs` that determines how to handle this.

@lmalina @JoschD @mihofer

**Comment by lmalina** [comment]
As Laurent mentioned there are many more types in MAD-NG, the question of compatibility with MAD-X seems to be the key point here.

**Comment by tpersson** [comment]
I think this should be really low priority considering the final implementation in MAD-NG is also unclear..
