### ISSUE TITLE
Writing crash on non-string column names

### ISSUE THREAD

**Issue by JoschD** [pylhc/tfs#62]
Writer crashes on non-string (or non iterable) column names.

```
ddf = tfs.TfsDataFrame([[1, 2.], [3, 4.]])
tfs.write_tfs('fdfsdf.tfs', ddf)

ddf
   0    1
0  1  2.0
1  3  4.0

```
leads to 

```
Traceback (most recent call last):
  File "tfs/handler.py", line 187, in write_tfs
    _validate(data_frame, f"to be written in {tfs_file_path.absolute()}")
  File "tfs/handler.py", line 474, in _validate
    if any(" " in c for c in data_frame.columns):
TypeError: argument of type 'int' is not iterable
```

- [ ] Fix
- [ ] WRITE TEST

**Comment by fsoubelet** [comment]
Predictably happens as (in the provided) example, `pandas` considers `ddf.columns` to be a `RangeIndex`.

A working fix would be to force the conversion, aka  in `_validate` using:
```python
if any(" " in c for c in data_frame.columns.to_numpy(dtype=str)):
```

However, while with this fix the provided example passes validation, I get back to the error reported in https://github.com/pylhc/tfs/issues/63
