### ISSUE TITLE
eol at eof ?

### ISSUE THREAD

**Issue by JoschD** [pylhc/tfs#86]
Should we add an eol (`\n`) at the end of the tfs file?

VIM is complaining and if you do `cat file.tfs` the next prompt starts directly after the values of the last column: 
![image](https://user-images.githubusercontent.com/26184899/127893788-fcf1da52-8961-4c72-83af-06637d543d6f.png)

To be tested if this is then still readable by a) us b) madx (which also has no eofeol)

**Comment by fsoubelet** [comment]
Could this be related to shell settings? I don't have this issue on my side:
<img width="878" alt="Screenshot 2021-08-02 at 20 59 54" src="https://user-images.githubusercontent.com/19598248/127910414-7bfaac84-ad5c-4e9f-948e-7afeaa1585b1.png">

**Comment by JoschD** [comment]
The shell part for sure. The general fact that there is no eol, which is standard in unix systems, not.
https://thoughtbot.com/blog/no-newline-at-end-of-file

**Comment by fsoubelet** [comment]
Quick test: modifying the `write_tfs` function and using `READTABLE` on TFS files with eoleof worked so far.

**Comment by fsoubelet** [comment]
Should I include this in #87 too? @JoschD @mihofer
